import sys
import json
import spacy
nlp = spacy.load("en_core_web_sm")

# Need to collect data for unrelated
TRAIN_DATA = [
    ("We appreciate your interest in Softrams and the position of Full-Stack Java Developer (Junior) for which you applied. We are reviewing applications currently. If you are shortlisted to continue to the interview process, one of our recruiters will be in contact with you. Thank you, again, for your interest in our company and taking the time to apply for our position.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We appreciate your interest in joining the Spectrum team. We often get an overwhelming response from individuals interested in our positions and we aren't able to review all of the applications that we received, and that's what happened here.  You can log into your candidate dashboard to confirm the status of your application for this job. While we realize this isn?t the outcome you were hoping for, we are still interested in connecting with you in the future.  We encourage you to use Fit Finder to discover other roles that match your skills and interests, and sign up for job alerts to be notified when those opportunities become available. Again, thank you for your interest in Spectrum. Please know that whatever you choose to connect to next, we wish you all the best!", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Raft and your application to the Software Engineer (Full Stack). Unfortunately, your application did not make it to the next phase of our hiring process.  We are extremely grateful for your submission and hope that we can connect again in the future.  Raft is continuously growing with new jobs, so please keep an eye out on our website. Thanks again for your interest in Raft and we wish you luck in your search.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying to Raft. We appreciate your application for the Software Engineer (Full Stack) position. Our current application review timeline is 3-5 days. If you have not received a message, please know that your candidacy remains open. We look forward to learning more about your journey!", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for the interest you expressed in the Software Developer - Intern R&D position at Hexagon's Asset Lifecycle Intelligence division located at our office in North Carolina - Home Office. At this time, we have decided to concentrate our attention on other candidates who we believe best meet the current needs of our organization. Please be assured that your application was given full consideration. If you have applied for other positions, please note that this message is only in reference to the Software Developer - Intern R&D 2023-11083. Your profile will be retained in our system in accordance with GDPR regulations, and if there are roles that we think you might be a good fit for, we will reach out to you. We also encourage you to visit our careers page using the link below to check for as new positions as they become available.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our open Software Engineering Intern position. Based on changing business needs, Leidos has decided not to go forward with filling this position. Leidos has many opportunities available that may fit your skills and interests. We encourage you to look at our career site at www.leidos.com/careers to find other career opportunities of interest to you.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the Software Engineering Intern (SWE) position - (Ref: iCIMS_131207). You’re one step closer to joining a team of 35,000 inquisitive minds on a quest to unlock solutions to the world’s most critical challenges! If you've applied directly, our recruitment team is reviewing your application and will contact you should there be a fit. If this email reached you because a recruiter identified your potential for this role, rest easy; there's no action needed on your part. Assuming our hiring manager agrees you're a match, we'll be in touch. For any updates or profile management, please access your candidate self service page. Thank you for considering Wood.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for the time and effort that you have put into your application. I’m so sorry for the inconvenience, but effective today, we will be pausing the internship search for summer 2024 indefinitely. You may have heard the news about Discord’s announced reduction in force. I want to provide some context around the decision. The decision was not made as a result of business concerns but instead to sharpen our focus and improve the way we deliver for our customers. Thank you again for your interest in Discord and we would love to stay connected for any future opportunities.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in a career at Workiva. We have received your application for the 2024 Summer - Software Engineer Intern (Ames, IA location) position. We will review your application and contact you in regards to the next step in the job application process. If we feel your skills and qualifications match what we are seeking for this position, a Recruiter or Hiring Manager will reach out to you directly.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying for the position of 01644691 Avionics Applications Software Engineering Co-op (Summer/Fall 2024) (On-site) . We have reviewed your skills, qualifications and experience; however, you were not selected to move forward in our hiring process at this time. We appreciate your interest and encourage you to visit https://jobs.rtx.com/ again to apply to any of our current openings.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the Product Lifecycle Supply Chain Project Specialist Internship - MSc (Meraki) position, Job ID 1416057. We appreciate the time and effort you have taken in applying for this role. We regret to inform you that we won't be moving forward with you in this position at this time. We may, however, reengage with you should another opportunity present itself. We encourage you to continue exploring a career path at Cisco as new roles pop up all the time. Finding other roles that match your skills and experience can be done by visiting https://jobs.cisco.com/ and signing in to set up job notifications that will notify you when new positions matching your interests open.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your career interest in Leonardo DRS. We appreciate the time you have taken to apply for the Spring 2024-Software Engineering Intern position. We have filled the position for which you have applied with another candidate who more closely matches our needs at this time.  We invite you to visit www.Leonardodrs.com/careers periodically to explore job opportunities. You may also create a personal Job Alert to automatically search for new positions that meets your search criteria and allows you to receive email notifications of potential career opportunities.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Wood and your application for the Software Engineering Intern (SWE) position in Austin, TX, United States. Your application has been reviewed against the criteria we have specified for this position and we regret to inform you that we are not going to proceed with your application. If you have applied for other opportunities, please note that this message is only in reference to iCIMS_131207, Software Engineering Intern (SWE), located in Austin, TX, United States. We will retain your details in the event that another opportunity becomes available that matches your skills and experience.  Please keep an eye out for any upcoming roles you may find suitable at Wood plc: https://careers.woodplc.com", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We regret to inform you that we will not be pursuing your candidacy for the Software Engineering Intern position. The selection process was highly competitive and we have decided to pursue other applicants whose background and experience more closely matches the requirements of the position. Again, we appreciate your interest, and encourage you to apply to other positions for which you may qualify. We wish you all the best in your future endeavors.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our Software Engineer Intern- Undergraduate Intern - JR89735 opportunity. We sincerely appreciate your interest in the company and the time you have spent during the application process. At this time, we are moving forward with another applicant. We encourage you to keep an eye on our careers page or sign up for our job alerts as we open new opportunities daily.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in working for Sierra Nevada Corporation. We received applications from many qualified individuals for the position of Software Engineering Intern -Multiple Roles (Summer 2024) . We regret to inform you that while your application was received and reviewed, you are not among those selected for further consideration. We encourage you to continue seeking employment within our organization, and hope that you are successful in your future endeavors.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for taking the time to apply to nou Systems .We really appreciate the effort you put into this. We received and have reviewed a number of applications. After reviewing them thoroughly, we identified other applicants whose skills and experience more closely matched the organization's needs. At this time, we have decided to move forward with other candidates. Thank you again for your interest in nou Systems. We wish you success in your job search.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Hope all is well and thanks again for your interest in Principal. We know there are many companies looking for talented professionals like you and we're happy you’ve chosen us as part of your career search. In selecting candidates to interview, our talent team considers a combination of factors including minimum and preferred qualifications along with resume alignment with the job scope. After reviewing your application for the Software Engineer Internship (Summer 2024) (2023-40528) position, we’ve made the difficult decision to move forward with other candidates at this time. While this position didn't work out, we hope you continue to keep Principal top of mind. We welcome you to visit our careers page to keep updated on future opportunities.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in BAE Systems. We are reaching out to let you know that Programmer Intern, Summer 2024, 95491BR has been cancelled. Please log into your candidate portal to check on the status of any other positions for which you applied. We encourage you to continue to browse our open positions as they become available. Thank you again for your interest in BAE Systems and we wish you success in your professional endeavors.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our Java Software Development Intern position at TRS.  We have received your application and if selected to move forward you will be contacted either by email or phone.  You can review your personal details and update your profile any time by visiting your profile here:", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We just received your information for our Intern, Software Engineer - Connectivity opening. We really appreciate you taking the time to consider us in your job search. We will review your submission right away and get back to you if we are able to move forward.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We have received your application for the Flight Software Engineering Intern position. We appreciate you taking the time to consider York Space Systems in your job search. We will review your submission as soon as we can and get back to you if we are able to move forward.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying to the position of  Associate Engineer NI Academy - 331677 on requisition number. We sincerely appreciate your interest in this position; however, our business requirements have changed, and the requisition has been cancelled.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our Software Engineer Intern- Undergraduate- Summer 2024 - JR89602 opportunity. We sincerely appreciate your interest in the company and the time you have spent during the application process. At this time, we are moving forward with another applicant. We encourage you to keep an eye on our careers page or sign up for our job alerts as we open new opportunities daily.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you completing the first steps on the path to becoming part of the FactSet Advantage! Your application for the Software Engineer Intern (Americas Campus - Summer 2024) position has been received and is now under review. If your background matches our needs for this position, someone from FactSet Talent Acquisition will be reaching out to you to discuss your background in more detail. Please be on the lookout for a follow up notification soon.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thanks for applying to Benchling. We've received your application for Software Engineer Intern (Summer 2024) and look forward to reviewing it. Our small (but mighty!) University Recruiting team reviews every application, so you'll receive an update on your application status within a few weeks.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thanks so much for your interest in Discord. We successfully received your application for the Software Engineer Intern - Perks (Core Product) role and are pumped to look over it. Our team will review your application and be in touch if your experiences are a fit for our role(s). If not, don't dismay - we always have new roles opening up so keep on checking back and trying!", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Figma! We know that applying for jobs takes time, and we appreciate your interest in joining our team. After reviewing your application, we've decided not to move forward with your candidacy at this time. Your resume is in our system for future opportunities, and we hope you'll keep an eye on our careers page. Best of luck with your job search!", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Figma! We wanted to let you know we received your application for the Software Engineer Intern (2024), and we are delighted that you would consider joining our team. While we’re not able to respond to every applicant, our recruiting team will contact you if your skills and experience are a strong match for the role. If you are not selected for this position, keep an eye on our jobs page as we’re growing and adding openings", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for allowing us to consider you for Summer Intern - Software Engineering at Allegion. Unfortunately, you are no longer being considered for this role, however we encourage you to continue to apply for other Allegion positions that you are qualified for at: Allegion Careers Site", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying to the Intern - Product Security Engineer position at Palo Alto Networks. Your application has been received. We’re excited that you want to take your career to the next level! You submitted your application via RippleMatch, a platform that Palo Alto Networks uses to quickly review your application and improve your candidate experience. You can track your application here. Someone from Palo Alto Networks’s team will review your application closely and will reach out via email if you are selected to move forward in the hiring process.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying at Cisco! We think it's a great place to work, and we're excited that you're interested in joining us as a Product Lifecycle Supply Chain Project Specialist Internship - MSc (Meraki), Job ID 1416057 here. What's next?  Please upload your resume to your Cisco Careers profile if you haven't done so already.  We'll use the information you provided and assess your background based on the role requirements. If there's a potential match for the position, we will contact you to discuss next steps. We may also use this information to consider you for future openings that match your skills and experience, in which case we would contact you directly. To update your profile, view application status, or search for other exciting opportunities, please visit our Cisco Careers. Meanwhile, keep checking for other roles that might match your interests, and even set up job alerts to notify you of any new openings.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying for the position of 01634613 Software Engineering Co-op (Summer/Fall 2024) (Hybrid) . We have reviewed your skills, qualifications and experience; however, you were not selected to move forward in our hiring process at this time. We appreciate your interest and encourage you to visit https://jobs.rtx.com/ again to apply to any of our current openings.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Your application for the position of Campus Undergraduate - 2024 Resy iOS Developer Summer Internship-23010020 has been received. If your application corresponds to the position requirements, a member of our recruiting team may contact you. If you would like to review your candidate file, Click here. What to Expect: Recruitment at American Express. American Express strives to provide a great candidate experience at every stage of consideration. We are interested in your feedback! Please click here to complete a 1-2 minute survey regarding the application process. Feedback is anonymized and is not visible to recruiters and hiring leaders.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying for the 2024 Data Analytics Intern-R00092994 position at AbbVie. We will review your experience and qualifications and if they match our requirements, a member of our Human Resources department will contact you soon. If you are aspiring to be a new AbbVie employee and would like to update your profile, click here. Also, you can withdraw your application from consideration or check the status of your previous submissions by clicking here. If you are a current AbbVie employee and would like to update your profile, click here. In addition, if you would like to withdraw your application from consideration or check the status of your previous submissions, click here. If you are a current Allergan employee and would like to update your profile, click here. In addition, if you would like to withdraw your application from consideration or check the status of your previous submissions, click here. At AbbVie, we strive to make a remarkable impact on the lives of patients. Thank you for your interest in joining us", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our Software Engineer Intern- Undergraduate- Summer 2024 - JR89603 opportunity. We sincerely appreciate your interest in the company and the time you have spent during the application process. At this time, we are moving forward with another applicant. We encourage you to keep an eye on our careers page or sign up for our job alerts as we open new opportunities daily.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We are fortunate to have many qualified candidates apply to each of our positions. We have reviewed the qualifications of each candidate and after careful consideration, we have determined that the credentials of other candidates may better fit our needs at this time for the Software Engineer Part-time Intern - Undergrad opening. Should your qualifications match the requirements of other openings you've applied to, you will be contacted by our Recruiting Team.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying for the New Product Introduction Engineering Intern, Hardware and Software  position, requisition number 2023-13605. We've reviewed your application and have narrowed our search to candidates whose background and experience more closely meet the position requirements. We encourage you to continue to visit our Keysight Careers Page and apply for other positions that may interest you.  Also, don't forget to register for Job Alerts to receive notifications of Keysight opportunities that match your interests.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your application for the Associate Engineer-NI Academy - 331572 position. We are excited to see how your strengths align with our vision for success. We invite you to participate in our HireVue assessment. This step is designed to provide you with an opportunity to showcase your unique talents and capabilities. This is a required step, so we strongly encourage you to complete the exercises below within the next 5 days. You will need 20 - 30 minutes to complete this step. Next Steps: In the HireVue evaluation you will be completing a video interview and game challenges. The video interview asks specific questions related to the role. You will be given time to prepare your answer to each question before recording. The game challenges have their own instructions that you will be able to read before playing. These exercises help us evaluate your fit for the role and understand how you think and process information. After you complete the HireVue process, we will provide you with a Candidate Insights Report designed to help you grow and develop for the future. ", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the 285411 Software Development Intern - Summer 2024 position at CACI. This requisition has been filled and therefore your application is no longer under consideration for this position. We sincerely appreciate your interest and encourage you to continue to review and apply for other opportunities at CACI by visiting our career site at", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Hope all is well and thanks again for your interest in Principal. We know there are many companies looking for talented professionals like you and we're happy you’ve chosen us as part of your career search. In selecting candidates to interview, our talent team considers a combination of factors including minimum and preferred qualifications along with resume alignment with the job scope. After reviewing your application for the Infrastructure Engineer Internship (2024) (2023-40531) position, we’ve made the difficult decision to move forward with other candidates at this time. While this position didn't work out, we hope you continue to keep Principal top of mind. We welcome you to visit our careers page to keep updated on future opportunities. We also encourage you to explore contractor roles at Principal. Thank you again for your interest in Principal. We look forward to seeing your application come through again in the future.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Johnson Controls. At this time, we regret to inform you that you have not been selected for the position of Software Engineering Intern ( WD30187658 ) We will keep your resume/CV on file and may consider you for future positions that align to your skills and experience.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in our Software Engineering Intern position. We appreciate your patience as we progress through our process. After reviewing your background, we have chosen not to move forward with your application at this time. We encourage you to visit our website at www.oshkoshcorporation.com/careers to view additional openings or set a job alert that will notify you of future openings.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thanks for applying to Google! There are a ton of great companies out there, so we appreciate your interest in joining our team. While we’re not able to reach out to every applicant, our recruiting team will contact you if your skills and experience are a strong match for the role. In the meantime, join the conversation about job opportunities and life at Google on our", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We appreciate your interest in Garmin and the time you invested applying with us. A member of our recruiting team has personally reviewed your application for our Software Engineer Intern opportunity. After careful consideration, you have not been selected to interview for this position. If you've applied to multiple positions, please note this decision only pertains to the job listed above. You can monitor the status of your application(s) by visiting your Profile Dashboard, at any time. Please keep in mind we are a dynamic and growing organization, so we invite you to visit our Careers Website regularly and apply for other positions which match your qualifications and interests. In the meantime, sign up for our Talent Network to stay updated on open positions.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for completing your video interview and for your interest in being part of the Lumen team! Our team is looking forward to reviewing your information and getting to know you a little bit better. No additional action on your part is required at this time. A member of our recruiting team will reach out to you if we are interested in moving forward with your application.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for submitting your information for the 2024 Summer Intern Program- Information Security Intern position. The Mr. Cooper Recruiting team is reviewing your qualifications and will contact you if there is a match with our current open positions. Meanwhile, using your email address and password, you can log into our Careers Site to update your application information or apply for other positions. You can also check the status of your application at any time.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in CACI and recent application to the following position(s):  • 286803 Software Development Intern - Summer 2024 Our CACI Talent Acquisition team is still in the process of reviewing your application, and a recruiter will contact you if you are determined to be a potential match for the position. To check the status of your application, visit Workday and log in to your account by selecting Sign In in the top right corner. Once logged in, you can view this and any other applications by clicking the cloud icon in the top right corner and navigating to View Profile.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your recent application for Technical Intern - Space Vehicle Security Engineer (32441). At this time, we have decided to move ahead with other candidates for this role.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Johnson Controls where we’re shaping the future to create a world that’s safe, comfortable and sustainable. This email is to confirm that we received your application for the position of Software Engineering Intern ( WD30187658 ). We are carefully reviewing your application and will be in touch regarding any potential next steps. You can also check for real time status updates on your application in our candidate portal at any time:", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in employment with Hexagon's Asset Lifecycle Intelligence division. We have reviewed your resume and have carefully considered your qualifications. While your skills and accomplishments are certainly impressive, we have decided to pursue other candidates for this position. Your profile will be retained in our system in accordance with GDPR regulations, and if there are roles that we think you might be a good fit for, we will reach out to you. We also encourage you to visit our careers page using the link below to check for as new positions as they become available.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for taking the time to consider a position with Epic. While we respect your achievements and appreciate your interest in applying, after careful consideration we've decided to move forward with other candidates. If circumstances change we may consider you for any appropriate positions that become available.  We appreciate the interest you have shown in Epic and wish you success in your career.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the 2024 software developer Summer Intern position at Parsons. We have decided to move forward with another candidate. Please visit our career site at https://jobs.parsons.com to view all of our available opportunities as well as set up job alerts. We appreciate your interest in Parsons and wish you success in your pursuit of a new opportunity.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in a career opportunity with Northrop Grumman. We have decided to move forward with other candidates for the position of 2024 Test Engineer Intern – San Diego, CA , requisition ID R10133357 2024 Test Engineer Intern – San Diego, CA (Evergreen) (Open) . New positions are posted daily, and we encourage you to apply for those that interest you and align with your experience and career goals. External candidates please use http://careers.northropgrumman.com and internal candidates please use https://www.myworkday.com/ngc/d/task/3005$4482.htmld. We recognize the time and effort it takes to explore new opportunities and appreciate your interest.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in ASML and the position of Internship - NI LabVIEW Programmer. We appreciate you’ve chosen to connect with us. Unfortunately, we decided to move forward with other candidates that are a stronger match for the role. We know how much effort goes into submitting an application and we really appreciate that you took the time to apply. But the journey doesn’t have to end here. We hope you will still consider ASML in the future and visit our careers page to explore other roles in line with your ambition and skill. You can also create personalized job alerts so you’re notified of new vacancies that may interest you. Please note that if you have applied for multiple ASML vacancies, you may still be in consideration for them. You can always check their status via your Candidate Home. Our close partners and suppliers are always looking for talented people to join our ecosystem of tech innovation, so make sure to discover job opportunities with them as well. We’d like to thank you again for your interest in ASML and wish you all the best in your career.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We're thrilled that you'd like to join us at Oshkosh! We now have your application for the Software Engineering Intern position. While we have not had a chance to review it yet, as this is an automated message telling you it made it across the internet, one of our recruiters will be taking a look at it soon and will be in touch if you are a good fit for the position. You can find out more about us on our company career page Oshkosh Careers. While we would love to meet with every applicant, unfortunately, we cannot. If you are not a match, we will let you know by email. We'll hang on to your resume and will be in touch if an opportunity opens up in the future. Also, don't hesitate to send us updates, join our talent community or sign up for job alerts.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying to Summer 2024 Avionics Software, Computer Science, Computer Science Engineering Intern - Graduate We received many outstanding applications for the few internships we have available. Unfortunately, we feel that your current background and experience are not the best match for the projects we will be conducting. Although we are unable to employ your skills at this time, we will continue offering internships in the future and I encourage you to reapply. If you are graduating and would like to apply for a full-time opportunity, you may do so from our website (https://www.blueorigin.com/careers). New Graduate candidates are encouraged to search for all opportunities that include the words Early Career in the title. Candidates may apply directly to one of our engineering teams (e.g. New Glenn, Blue Engines) or may choose to apply to the New Graduate Rotation Program.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the Internship 2024 NIC BU Aerospace Engineer  (#2312534) position at SAIC.  The initial selection process has been completed and regretfully, you have not been selected for an interview. We encourage you to look at future openings that match your professional interests and qualifications.  New positions are opened daily so be sure to check our career website for additional opportunities. At SAIC, we believe that putting people first is the right thing to do.  That’s why we’ve brought you the best job searching tools all in one place!  Take advantage of these Job Search Assistance Tools to help you right away.  This is a free platform, powered by SAIC.  When you register, you will have access to resume development, interview practices, self-assessments and more!  This platform is available 24 hours a day, 7 days a week. We sincerely wish you success in your job search.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thanks for your interest in Information Security Intern- Summer 2024 on WayUp! Have you completed the second part of the application process on Stifel Financial Corp.'s site?", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the Information Security Intern- Summer 2024 position with Stifel, Nicolaus & Co., Inc.. Your application has been received and a member of our HR Talent Acquisition Staff will review your information shortly. Should your profile meet the qualifications for the role, a member of our team will reach out. We’re thrilled you have taken the time to apply for a role at Stifel, Nicolaus & Co., Inc..", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We received your job application for IT Software Development Co-Op - Spring 2025 - 2723. If your profile corresponds to our requirements, a member of our Recruiting team will contact you. If you were requested to provide additional info about your job application, or if you want to manage your profile, go to your candidate self service page.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in working with us at Leidos! Your application for the position of Software Engineering Intern is being reviewed and a recruiter will reach out if we are moving forward with your application. In the meantime, you can also see the status of your application on your Workday Home Account by logging in to Workday. This will also allow you to apply to additional opportunities.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thanks very much for your interest in our opening, R6534 Software Engineering Intern. We hired someone for this position before having a chance to consider your application for this role. We hope you’ll consider visiting our career site https://careers.conmed.com/ to see if there are other openings that might be a good match. You can also sign up for our Talent Community (https://careers.conmed.com/jointalentcommunity?applyType=JTC) to be alerted to future opportunities that may be a match.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for taking the time to submit your application for our iOS or Android Application Engineer Intern opening. We are excited to start this journey together! Our team is carefully reviewing your application for this exciting opportunity. Should your experience and background match our needs, a member of our Talent Acquisition team will reach out directly to continue the process. Thanks again for your interest and consideration.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your application! We are excited about your interest in joining BAE Systems to help protect those who protect us and innovate for those that move the world. Over the coming weeks, our Talent Acquisition team will be evaluating applications for this role and will make contact with you should your application be compatible with the requirements. In the meantime, you can use this link to check your application status and manage your profile.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in Allison Transmission. If there is a match between your profile and the job requirements, a Recruiter will reach out with further details.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you very much for your recent application to HMADH01-Dedham-150 Rustcraft Road. Your resume will be reviewed by our recruiting staff, and we will contact you soon, should we feel that your background meets our current needs. To ensure you continue to receive email messages, please add “@agents.icims.com” to your email safe senders.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your application for the role of System Engineer Intern and for your interest in Valeo's opportunities. We have carefully reviewed it and we regret to inform you that we cannot give a favorable follow-up to your application. However, your application shows real advantages and is likely in the medium term to correspond to our recruitment needs. We therefore keep your file and we will contact you when an opportunity arises. We also invite you to update your application on our website according to your willing.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("We have received your application for the position of Intern, Software Systems Design Engineering and are currently reviewing your experience and qualifications. If your profile corresponds to our requirements, a member of our Talent Acquisition Department will contact you soon. We thank you for your interest in Analog Devices.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for applying to the Johns Hopkins Applied Physics Laboratory. We appreciate your time and your interest in APL! Now that you’ve applied to APL you probably wonder what will happen next? Our Talent Acquisition team will review your application and, if you meet the qualifications for the role, we will share your information with hiring teams who are looking for people with your skillset. You can monitor your application and update your information on your candidate dashboard. During the review process you may see new positions appear on your dashboard—this is normal as we uncover additional positions that may be a fit for you. At APL, we solve complex problems that present critical challenges to our Nation. We’re so excited that you’ve taken the first step toward exploring a career with us!", {"cats": {"related": 1.0, "unrelated": 0.0}}),
    ("Thank you for your interest in the Site Reliability Engineer, Intern - Summer 2024 position. We’ve reviewed your background and experience and unfortunately, we have decided to move ahead with other candidates. We appreciate the time you took to apply and encourage you not to let this be the end of your exploration of careers at Visa! We’re growing and adding new roles on a regular basis, so we invite you to explore the Careers page on visa.com/careers for another great opportunity to pursue. Good luck to you in your search and we hope to be in touch again in the future.", {"cats": {"related": 1.0, "unrelated": 0.0}}),
]

def your_python_function(data):
    # Process the data
    return {"processed": data}

def normalize_text(text):
    text = text.lower()
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if not token.is_punct and not token.is_stop and token.is_alpha]
    normalized_text = " ".join(tokens)
    return normalized_text

if __name__ == '__main__':
    input_data = sys.stdin.read()
    data = json.loads(input_data)
    result = your_python_function(data)
    print(json.dumps(result))